### ISSUE TITLE
less imports

### ISSUE THREAD

**Issue by MasseGuillaume** [abe33/atom-color-highlight#28]
base.less

``` less
@black: black;
```

other.less

``` less
import 'base.less';
* {
  color: @black;
}
```

other.less `@black` is colored
