### ISSUE TITLE
Use underline instead of background

### ISSUE THREAD

**Issue by lekhnath** [abe33/atom-color-highlight#82]
I think it would be nice to use `underline` to show the actual color instead of `background`. Can I do some customization to be able to do this thing in my local.

**Comment by abe33** [comment]
Sure, something like that should do the trick: 

```css
atom-text-editor atom-color-highlight .region, atom-text-editor::shadow atom-color-highlight .region {
  height: 2px;
  margin-top: 1.3em; // adjust to your liking
  overflow: hidden
}
```
